# Generated by Django 3.1.7 on 2021-05-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='section_one',
            new_name='text_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section_three',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section_two',
        ),
    ]
