# Generated by Django 3.1.7 on 2021-05-16 18:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210510_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
